-- v7.73 — Chewy sales file mapping check
-- Run on Supabase → SQL Editor. Shows which Chewy SKUs in the uploaded
-- weekly-actuals file DO / DON'T map to products.chewy_sku.
--
-- Run each of the three queries below in order. Each one is independent.

-- ═══════════════════════════════════════════════════════════════
-- Query 1 — SUMMARY: how many of the 81 Chewy SKUs in the file
-- have a matching row in products.chewy_sku
-- ═══════════════════════════════════════════════════════════════
with file_skus(chewy_sku, sample_name) as (values
  ('1105126', 'Meowijuana Refillable Get Sprung Ladybug Cat Plush Toy with Catnip'),
  ('1105134', 'Meowijuana Refillable Get Spooked Pumpkin Cat Plush Toy with Catnip'),
  ('1105150', 'Meowijuana Refillable Get Sprung Strawberry Cat Plush Toy with Catnip'),
  ('1105182', 'Meowijuana Jump ''n'' Jamb Get Wild Sloth Refillable Swinging Door Jamb Cat Plush Toy with Catnip'),
  ('1105198', 'Meowijuana Refillable Get Silly Ruby Rascal Cat Plush Toy with Catnip'),
  ('1105214', 'Meowijuana Refillable Get Silly Blue Blob Cat Plush Toy with Catnip'),
  ('1105230', 'Meowijuana Refillable Get Sprung Duckling Cat Plush Toy with Catnip'),
  ('1105246', 'Meowijuana Refillable Get Kickin'' Spicy Pickle Kicker Cat Plush Toy with Catnip'),
  ('125628', 'Meowijuana Jar of Organic Catnibas Catnip Buds, 20-g jar'),
  ('125631', 'Meowijuana Meowi-Waui Catnip, Large'),
  ('125633', 'Meowijuana Catnibas King Size Rollies'),
  ('125636', 'Meowijuana Catnip Spray, 1-oz bottle'),
  ('1271726', 'Meowijuana Santa''s Secret Stash Peppermint, Cranberry, Silvervine Blend Catnip, 20-g tube'),
  ('1271734', 'Meowijuana Crunchie Munchie Seafood Medley Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1271742', 'Meowijuana Cloud 9 Sunflower Petal, Rose Petal & Marshmallow Leaf Blend Catnip, 26-g bottle'),
  ('1271758', 'Meowijuana Crunchie Munchie Chicken Flavored Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1294182', 'Meowijuana Get Kickin'' Refillable Gummy Worm Plush Cat Toy with Catnip'),
  ('1294198', 'Meowijuana Knock ''n'' Nibble Avocado Refillable Treat Dispensing Cat Toy'),
  ('1294214', 'Meowijuana Knock ''n'' Nibble Starfish Refillable Treat Dispensing Cat Toy'),
  ('1294294', 'Meowijuana Get Silly Refillable Furry Friend Plush Cat Toy with Catnip, Yellow'),
  ('156565', 'Meowijuana Kalico Kush Catnip & Valerian Root Blend Catnip, 0.917-oz bottle'),
  ('156567', 'Meowijuana Purrple Passion Catnip & Silvervine Blend Catnip, 0.917-oz bottle'),
  ('156569', 'Meowijuana Mice Dreams Catnip, Passion Flower, & Lavender Blend Catnip, 0.917-oz bottle'),
  ('156570', 'Meowijuana Catnip Spray, 3-oz bottle'),
  ('156572', 'Meowijuana Catnip Cigar Cat Toy, Color Varies'),
  ('161576', 'Meowijuana Jar of Catnibas Catnip Pawty Mix, 60-g jar'),
  ('1702750', 'Meowijuana Get Sprung Marvelous Mushroom Cat Plush Toy with Catnip'),
  ('1702766', 'Meowijuana Get Sprung Funny Frog Cat Plush Toy with Catnip'),
  ('1702790', 'Meowijuana Knock ''n'' Nibble Strawberry Cat Treat Dispensing Toy'),
  ('1702806', 'Meowijuana Get Sprung Hungry Caterpillar Cat Plush Toy with Catnip'),
  ('1702814', 'Meowijuana Jump ''n'' Jamb Flashy Dragonfly Cat Teaser Toy with Catnip'),
  ('1702846', 'Meowijuana Silvervine Fruit Sticks Cat Chew Toy'),
  ('181282', 'Meowijuana Refillable Get Smoked Catnip Fish Cat Toy'),
  ('181284', 'Meowijuana Refillable Get Baked Catnip Cookie Cat Toy'),
  ('181288', 'Meowijuana Whisker Tickler Catnip, Chamomile, & Dandelion Blend, 26-gram bottle'),
  ('181290', 'Meowijuana King Sized Silvervine Cat Sticks, 6 count'),
  ('181292', 'Meowijuana Refillable Get Buzzed Catnip Bee Cat Toy'),
  ('1993126', 'Meowijuana Kalico Kush Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993142', 'Meowijuana Purrple Passion Compressed Catnip Ball Refill, 2 count'),
  ('1993166', 'Meowijuana Kalico Kush Compressed Catnip Ball Refill, 2 count'),
  ('1993182', 'Meowijuana Purple Passion Whack ''n'' Roll Compressed Catnip Ball with Cage'),
  ('1993190', 'Meowijuana Purrple Passion Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993206', 'Meowijuana Lollies Silvervine Sticks with Catnip, 3 count'),
  ('235814', 'Meowijuana Feline Frost Catnip, Silvervine, & Peppermint Blend Catnip, 26-gram bottle'),
  ('235816', 'Meowijuana Catnip Oil Honeysuckle Spray, 3-oz bottle'),
  ('3271606', 'Meowijuana Get Noodly Noodles & Sriracha Catnip Cat Toy, 2 count'),
  ('3271638', 'Meowijuana Sprinkle ''n'' Scratch Taco Scratcher Cat Toy'),
  ('3271646', 'Meowijuana Get Celebrated Cake & Hat Catnip Cat Toy, 2 count'),
  ('3271662', 'Meowijuana Get Spicy Taco Margarita Catnip Cat Toy, 2 count'),
  ('346154', 'Meowijuana Happy Grass Lemongrass Blend Catnip, 0.92-oz bottle'),
  ('346156', 'Meowijuana Skull Cap Blend Catnip, 0.92-oz bottle'),
  ('346158', 'Meowijuana Garden Pawty Dill, Parsley & Valerian Root Blend Catnip, 0.92-oz bottle'),
  ('346160', 'Meowijuana Thyme Out Blend Catnip, 0.92-oz bottle'),
  ('346162', 'Meowijuana Honeysuckle Haze Blend Catnip, 0.92-oz bottle'),
  ('346164', 'Meowijuana Birthjays Party Sized Catnip Joints, 1 count'),
  ('346166', 'Meowijuana Bubbles with Honeysuckle Catnip, 5-oz bottle'),
  ('3500990', 'Meowijuana Christmas Knock ''N'' Nibble Winter Buddy Plush Cat Toy with Catnip, Brown/Blue, Small'),
  ('3501014', 'Meowijuana Get Nogged Winter Eggnog Plush Cat Toy with Catnip, Orange, Small'),
  ('3506998', 'Meowijuana Crunchie Munchies Salmon Flavored Cat Treats, 3-oz bag'),
  ('363602', 'Meowijuana Get Blitzed Reindeer Refillable Plush Cat Toy with Catnip'),
  ('363604', 'Meowijuana Get Higher than a Kite Wand Refillable Plush Cat Toy with Catnip'),
  ('363610', 'Meowijuana Get a Rise Balloon Refillable Plush Cat Toy with Catnip'),
  ('363612', 'Meowijuana Get Cheesy Mouse & Cheese Refillable Plush Cat Toy with Catnip'),
  ('363614', 'Meowijuana Get Chilled Snowcone Refillable Plush Cat Toy with Catnip'),
  ('363616', 'Meowijuana Get Hooked Big Kahuna Tuna Refillable Plush Cat Toy with Catnip'),
  ('4566958', 'Meowijuana Get Sporty Soccer Ball & Cleat Refillable Plush Cat Toy with Catnip, Blue, Small, 2 count'),
  ('4567230', 'Meowijuana Get Salty Stingray Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('4567238', 'Meowijuana Get Salty Sea Turtle Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('692518', 'Meowijuana Sierra Sunshine Sunflower, Honeysuckle, Silvervine Catnip Blend, 26-gm bottle'),
  ('696582', 'Meowijuana Jump ''n'' Jamb Get the Monkey Off Your Back Refillable Swinging Door Jamb Cat Toy'),
  ('696598', 'Meowijuana Jump ''n'' Jamb Deep Sea Squid Refillable Swinging Door Jamb Cat Toy'),
  ('696614', 'Meowijuana Refillable Get Hung Moon & Stars Cat Toy'),
  ('696630', 'Meowijuana Refillable Get Lit Cake Cat Toy'),
  ('696646', 'Meowijuana Refillable Get Smashed Llama Pinata Wand Cat Toy'),
  ('696662', 'Meowijuana Refillable Get Wrapped Sushi Cat Toy'),
  ('696678', 'Meowijuana Refillable Get a Ride Magic Carpet Cat Toy'),
  ('696694', 'Meowijuana Christmas Refillable Get Twisted Candy Cane Cat Toy'),
  ('696710', 'Meowijuana Christmas Refillable Get Stuffed Stocking Cat Toy'),
  ('930406', 'Meowijuana Catnip & Silvervine Spray, 3-oz bottle'),
  ('964630', 'Meowijuana Winter Lift Peppermint, Cranberry, Silvervine, & Catnip Blend Catnip, 26-g jar'),
  ('984614', 'Meowijuana Jar of Catnibas Catnip Pawty Mix with Lemongrass Cat Catnip, 60-g bag')
),
matched as (
  select f.chewy_sku, f.sample_name, p.master_id, p.short_name, p.brand, p.active
  from file_skus f
  left join products p on p.chewy_sku = f.chewy_sku
)
select
  count(*)                                        as total_in_file,
  count(master_id)                                as matched,
  count(*) - count(master_id)                     as unmatched,
  count(*) filter (where active = false)          as matched_but_inactive
from matched;


-- ═══════════════════════════════════════════════════════════════
-- Query 2 — Detail: unmatched Chewy SKUs (need product records or
-- their chewy_sku assigned)
-- ═══════════════════════════════════════════════════════════════
with file_skus(chewy_sku, sample_name) as (values
  ('1105126', 'Meowijuana Refillable Get Sprung Ladybug Cat Plush Toy with Catnip'),
  ('1105134', 'Meowijuana Refillable Get Spooked Pumpkin Cat Plush Toy with Catnip'),
  ('1105150', 'Meowijuana Refillable Get Sprung Strawberry Cat Plush Toy with Catnip'),
  ('1105182', 'Meowijuana Jump ''n'' Jamb Get Wild Sloth Refillable Swinging Door Jamb Cat Plush Toy with Catnip'),
  ('1105198', 'Meowijuana Refillable Get Silly Ruby Rascal Cat Plush Toy with Catnip'),
  ('1105214', 'Meowijuana Refillable Get Silly Blue Blob Cat Plush Toy with Catnip'),
  ('1105230', 'Meowijuana Refillable Get Sprung Duckling Cat Plush Toy with Catnip'),
  ('1105246', 'Meowijuana Refillable Get Kickin'' Spicy Pickle Kicker Cat Plush Toy with Catnip'),
  ('125628', 'Meowijuana Jar of Organic Catnibas Catnip Buds, 20-g jar'),
  ('125631', 'Meowijuana Meowi-Waui Catnip, Large'),
  ('125633', 'Meowijuana Catnibas King Size Rollies'),
  ('125636', 'Meowijuana Catnip Spray, 1-oz bottle'),
  ('1271726', 'Meowijuana Santa''s Secret Stash Peppermint, Cranberry, Silvervine Blend Catnip, 20-g tube'),
  ('1271734', 'Meowijuana Crunchie Munchie Seafood Medley Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1271742', 'Meowijuana Cloud 9 Sunflower Petal, Rose Petal & Marshmallow Leaf Blend Catnip, 26-g bottle'),
  ('1271758', 'Meowijuana Crunchie Munchie Chicken Flavored Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1294182', 'Meowijuana Get Kickin'' Refillable Gummy Worm Plush Cat Toy with Catnip'),
  ('1294198', 'Meowijuana Knock ''n'' Nibble Avocado Refillable Treat Dispensing Cat Toy'),
  ('1294214', 'Meowijuana Knock ''n'' Nibble Starfish Refillable Treat Dispensing Cat Toy'),
  ('1294294', 'Meowijuana Get Silly Refillable Furry Friend Plush Cat Toy with Catnip, Yellow'),
  ('156565', 'Meowijuana Kalico Kush Catnip & Valerian Root Blend Catnip, 0.917-oz bottle'),
  ('156567', 'Meowijuana Purrple Passion Catnip & Silvervine Blend Catnip, 0.917-oz bottle'),
  ('156569', 'Meowijuana Mice Dreams Catnip, Passion Flower, & Lavender Blend Catnip, 0.917-oz bottle'),
  ('156570', 'Meowijuana Catnip Spray, 3-oz bottle'),
  ('156572', 'Meowijuana Catnip Cigar Cat Toy, Color Varies'),
  ('161576', 'Meowijuana Jar of Catnibas Catnip Pawty Mix, 60-g jar'),
  ('1702750', 'Meowijuana Get Sprung Marvelous Mushroom Cat Plush Toy with Catnip'),
  ('1702766', 'Meowijuana Get Sprung Funny Frog Cat Plush Toy with Catnip'),
  ('1702790', 'Meowijuana Knock ''n'' Nibble Strawberry Cat Treat Dispensing Toy'),
  ('1702806', 'Meowijuana Get Sprung Hungry Caterpillar Cat Plush Toy with Catnip'),
  ('1702814', 'Meowijuana Jump ''n'' Jamb Flashy Dragonfly Cat Teaser Toy with Catnip'),
  ('1702846', 'Meowijuana Silvervine Fruit Sticks Cat Chew Toy'),
  ('181282', 'Meowijuana Refillable Get Smoked Catnip Fish Cat Toy'),
  ('181284', 'Meowijuana Refillable Get Baked Catnip Cookie Cat Toy'),
  ('181288', 'Meowijuana Whisker Tickler Catnip, Chamomile, & Dandelion Blend, 26-gram bottle'),
  ('181290', 'Meowijuana King Sized Silvervine Cat Sticks, 6 count'),
  ('181292', 'Meowijuana Refillable Get Buzzed Catnip Bee Cat Toy'),
  ('1993126', 'Meowijuana Kalico Kush Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993142', 'Meowijuana Purrple Passion Compressed Catnip Ball Refill, 2 count'),
  ('1993166', 'Meowijuana Kalico Kush Compressed Catnip Ball Refill, 2 count'),
  ('1993182', 'Meowijuana Purple Passion Whack ''n'' Roll Compressed Catnip Ball with Cage'),
  ('1993190', 'Meowijuana Purrple Passion Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993206', 'Meowijuana Lollies Silvervine Sticks with Catnip, 3 count'),
  ('235814', 'Meowijuana Feline Frost Catnip, Silvervine, & Peppermint Blend Catnip, 26-gram bottle'),
  ('235816', 'Meowijuana Catnip Oil Honeysuckle Spray, 3-oz bottle'),
  ('3271606', 'Meowijuana Get Noodly Noodles & Sriracha Catnip Cat Toy, 2 count'),
  ('3271638', 'Meowijuana Sprinkle ''n'' Scratch Taco Scratcher Cat Toy'),
  ('3271646', 'Meowijuana Get Celebrated Cake & Hat Catnip Cat Toy, 2 count'),
  ('3271662', 'Meowijuana Get Spicy Taco Margarita Catnip Cat Toy, 2 count'),
  ('346154', 'Meowijuana Happy Grass Lemongrass Blend Catnip, 0.92-oz bottle'),
  ('346156', 'Meowijuana Skull Cap Blend Catnip, 0.92-oz bottle'),
  ('346158', 'Meowijuana Garden Pawty Dill, Parsley & Valerian Root Blend Catnip, 0.92-oz bottle'),
  ('346160', 'Meowijuana Thyme Out Blend Catnip, 0.92-oz bottle'),
  ('346162', 'Meowijuana Honeysuckle Haze Blend Catnip, 0.92-oz bottle'),
  ('346164', 'Meowijuana Birthjays Party Sized Catnip Joints, 1 count'),
  ('346166', 'Meowijuana Bubbles with Honeysuckle Catnip, 5-oz bottle'),
  ('3500990', 'Meowijuana Christmas Knock ''N'' Nibble Winter Buddy Plush Cat Toy with Catnip, Brown/Blue, Small'),
  ('3501014', 'Meowijuana Get Nogged Winter Eggnog Plush Cat Toy with Catnip, Orange, Small'),
  ('3506998', 'Meowijuana Crunchie Munchies Salmon Flavored Cat Treats, 3-oz bag'),
  ('363602', 'Meowijuana Get Blitzed Reindeer Refillable Plush Cat Toy with Catnip'),
  ('363604', 'Meowijuana Get Higher than a Kite Wand Refillable Plush Cat Toy with Catnip'),
  ('363610', 'Meowijuana Get a Rise Balloon Refillable Plush Cat Toy with Catnip'),
  ('363612', 'Meowijuana Get Cheesy Mouse & Cheese Refillable Plush Cat Toy with Catnip'),
  ('363614', 'Meowijuana Get Chilled Snowcone Refillable Plush Cat Toy with Catnip'),
  ('363616', 'Meowijuana Get Hooked Big Kahuna Tuna Refillable Plush Cat Toy with Catnip'),
  ('4566958', 'Meowijuana Get Sporty Soccer Ball & Cleat Refillable Plush Cat Toy with Catnip, Blue, Small, 2 count'),
  ('4567230', 'Meowijuana Get Salty Stingray Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('4567238', 'Meowijuana Get Salty Sea Turtle Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('692518', 'Meowijuana Sierra Sunshine Sunflower, Honeysuckle, Silvervine Catnip Blend, 26-gm bottle'),
  ('696582', 'Meowijuana Jump ''n'' Jamb Get the Monkey Off Your Back Refillable Swinging Door Jamb Cat Toy'),
  ('696598', 'Meowijuana Jump ''n'' Jamb Deep Sea Squid Refillable Swinging Door Jamb Cat Toy'),
  ('696614', 'Meowijuana Refillable Get Hung Moon & Stars Cat Toy'),
  ('696630', 'Meowijuana Refillable Get Lit Cake Cat Toy'),
  ('696646', 'Meowijuana Refillable Get Smashed Llama Pinata Wand Cat Toy'),
  ('696662', 'Meowijuana Refillable Get Wrapped Sushi Cat Toy'),
  ('696678', 'Meowijuana Refillable Get a Ride Magic Carpet Cat Toy'),
  ('696694', 'Meowijuana Christmas Refillable Get Twisted Candy Cane Cat Toy'),
  ('696710', 'Meowijuana Christmas Refillable Get Stuffed Stocking Cat Toy'),
  ('930406', 'Meowijuana Catnip & Silvervine Spray, 3-oz bottle'),
  ('964630', 'Meowijuana Winter Lift Peppermint, Cranberry, Silvervine, & Catnip Blend Catnip, 26-g jar'),
  ('984614', 'Meowijuana Jar of Catnibas Catnip Pawty Mix with Lemongrass Cat Catnip, 60-g bag')
)
select f.chewy_sku, f.sample_name
from file_skus f
left join products p on p.chewy_sku = f.chewy_sku
where p.master_id is null
order by f.chewy_sku;


-- ═══════════════════════════════════════════════════════════════
-- Query 3 — Detail: matched but inactive (rare — shouldn't be receiving
-- Chewy shipments if flagged inactive on Products page)
-- ═══════════════════════════════════════════════════════════════
with file_skus(chewy_sku, sample_name) as (values
  ('1105126', 'Meowijuana Refillable Get Sprung Ladybug Cat Plush Toy with Catnip'),
  ('1105134', 'Meowijuana Refillable Get Spooked Pumpkin Cat Plush Toy with Catnip'),
  ('1105150', 'Meowijuana Refillable Get Sprung Strawberry Cat Plush Toy with Catnip'),
  ('1105182', 'Meowijuana Jump ''n'' Jamb Get Wild Sloth Refillable Swinging Door Jamb Cat Plush Toy with Catnip'),
  ('1105198', 'Meowijuana Refillable Get Silly Ruby Rascal Cat Plush Toy with Catnip'),
  ('1105214', 'Meowijuana Refillable Get Silly Blue Blob Cat Plush Toy with Catnip'),
  ('1105230', 'Meowijuana Refillable Get Sprung Duckling Cat Plush Toy with Catnip'),
  ('1105246', 'Meowijuana Refillable Get Kickin'' Spicy Pickle Kicker Cat Plush Toy with Catnip'),
  ('125628', 'Meowijuana Jar of Organic Catnibas Catnip Buds, 20-g jar'),
  ('125631', 'Meowijuana Meowi-Waui Catnip, Large'),
  ('125633', 'Meowijuana Catnibas King Size Rollies'),
  ('125636', 'Meowijuana Catnip Spray, 1-oz bottle'),
  ('1271726', 'Meowijuana Santa''s Secret Stash Peppermint, Cranberry, Silvervine Blend Catnip, 20-g tube'),
  ('1271734', 'Meowijuana Crunchie Munchie Seafood Medley Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1271742', 'Meowijuana Cloud 9 Sunflower Petal, Rose Petal & Marshmallow Leaf Blend Catnip, 26-g bottle'),
  ('1271758', 'Meowijuana Crunchie Munchie Chicken Flavored Catnip Crunchy Cat Treats, 3-oz bag'),
  ('1294182', 'Meowijuana Get Kickin'' Refillable Gummy Worm Plush Cat Toy with Catnip'),
  ('1294198', 'Meowijuana Knock ''n'' Nibble Avocado Refillable Treat Dispensing Cat Toy'),
  ('1294214', 'Meowijuana Knock ''n'' Nibble Starfish Refillable Treat Dispensing Cat Toy'),
  ('1294294', 'Meowijuana Get Silly Refillable Furry Friend Plush Cat Toy with Catnip, Yellow'),
  ('156565', 'Meowijuana Kalico Kush Catnip & Valerian Root Blend Catnip, 0.917-oz bottle'),
  ('156567', 'Meowijuana Purrple Passion Catnip & Silvervine Blend Catnip, 0.917-oz bottle'),
  ('156569', 'Meowijuana Mice Dreams Catnip, Passion Flower, & Lavender Blend Catnip, 0.917-oz bottle'),
  ('156570', 'Meowijuana Catnip Spray, 3-oz bottle'),
  ('156572', 'Meowijuana Catnip Cigar Cat Toy, Color Varies'),
  ('161576', 'Meowijuana Jar of Catnibas Catnip Pawty Mix, 60-g jar'),
  ('1702750', 'Meowijuana Get Sprung Marvelous Mushroom Cat Plush Toy with Catnip'),
  ('1702766', 'Meowijuana Get Sprung Funny Frog Cat Plush Toy with Catnip'),
  ('1702790', 'Meowijuana Knock ''n'' Nibble Strawberry Cat Treat Dispensing Toy'),
  ('1702806', 'Meowijuana Get Sprung Hungry Caterpillar Cat Plush Toy with Catnip'),
  ('1702814', 'Meowijuana Jump ''n'' Jamb Flashy Dragonfly Cat Teaser Toy with Catnip'),
  ('1702846', 'Meowijuana Silvervine Fruit Sticks Cat Chew Toy'),
  ('181282', 'Meowijuana Refillable Get Smoked Catnip Fish Cat Toy'),
  ('181284', 'Meowijuana Refillable Get Baked Catnip Cookie Cat Toy'),
  ('181288', 'Meowijuana Whisker Tickler Catnip, Chamomile, & Dandelion Blend, 26-gram bottle'),
  ('181290', 'Meowijuana King Sized Silvervine Cat Sticks, 6 count'),
  ('181292', 'Meowijuana Refillable Get Buzzed Catnip Bee Cat Toy'),
  ('1993126', 'Meowijuana Kalico Kush Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993142', 'Meowijuana Purrple Passion Compressed Catnip Ball Refill, 2 count'),
  ('1993166', 'Meowijuana Kalico Kush Compressed Catnip Ball Refill, 2 count'),
  ('1993182', 'Meowijuana Purple Passion Whack ''n'' Roll Compressed Catnip Ball with Cage'),
  ('1993190', 'Meowijuana Purrple Passion Stick ''n'' Lick Compressed Catnip, 2 count'),
  ('1993206', 'Meowijuana Lollies Silvervine Sticks with Catnip, 3 count'),
  ('235814', 'Meowijuana Feline Frost Catnip, Silvervine, & Peppermint Blend Catnip, 26-gram bottle'),
  ('235816', 'Meowijuana Catnip Oil Honeysuckle Spray, 3-oz bottle'),
  ('3271606', 'Meowijuana Get Noodly Noodles & Sriracha Catnip Cat Toy, 2 count'),
  ('3271638', 'Meowijuana Sprinkle ''n'' Scratch Taco Scratcher Cat Toy'),
  ('3271646', 'Meowijuana Get Celebrated Cake & Hat Catnip Cat Toy, 2 count'),
  ('3271662', 'Meowijuana Get Spicy Taco Margarita Catnip Cat Toy, 2 count'),
  ('346154', 'Meowijuana Happy Grass Lemongrass Blend Catnip, 0.92-oz bottle'),
  ('346156', 'Meowijuana Skull Cap Blend Catnip, 0.92-oz bottle'),
  ('346158', 'Meowijuana Garden Pawty Dill, Parsley & Valerian Root Blend Catnip, 0.92-oz bottle'),
  ('346160', 'Meowijuana Thyme Out Blend Catnip, 0.92-oz bottle'),
  ('346162', 'Meowijuana Honeysuckle Haze Blend Catnip, 0.92-oz bottle'),
  ('346164', 'Meowijuana Birthjays Party Sized Catnip Joints, 1 count'),
  ('346166', 'Meowijuana Bubbles with Honeysuckle Catnip, 5-oz bottle'),
  ('3500990', 'Meowijuana Christmas Knock ''N'' Nibble Winter Buddy Plush Cat Toy with Catnip, Brown/Blue, Small'),
  ('3501014', 'Meowijuana Get Nogged Winter Eggnog Plush Cat Toy with Catnip, Orange, Small'),
  ('3506998', 'Meowijuana Crunchie Munchies Salmon Flavored Cat Treats, 3-oz bag'),
  ('363602', 'Meowijuana Get Blitzed Reindeer Refillable Plush Cat Toy with Catnip'),
  ('363604', 'Meowijuana Get Higher than a Kite Wand Refillable Plush Cat Toy with Catnip'),
  ('363610', 'Meowijuana Get a Rise Balloon Refillable Plush Cat Toy with Catnip'),
  ('363612', 'Meowijuana Get Cheesy Mouse & Cheese Refillable Plush Cat Toy with Catnip'),
  ('363614', 'Meowijuana Get Chilled Snowcone Refillable Plush Cat Toy with Catnip'),
  ('363616', 'Meowijuana Get Hooked Big Kahuna Tuna Refillable Plush Cat Toy with Catnip'),
  ('4566958', 'Meowijuana Get Sporty Soccer Ball & Cleat Refillable Plush Cat Toy with Catnip, Blue, Small, 2 count'),
  ('4567230', 'Meowijuana Get Salty Stingray Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('4567238', 'Meowijuana Get Salty Sea Turtle Refillable Plush Cat Toy with Catnip, Blue, Medium'),
  ('692518', 'Meowijuana Sierra Sunshine Sunflower, Honeysuckle, Silvervine Catnip Blend, 26-gm bottle'),
  ('696582', 'Meowijuana Jump ''n'' Jamb Get the Monkey Off Your Back Refillable Swinging Door Jamb Cat Toy'),
  ('696598', 'Meowijuana Jump ''n'' Jamb Deep Sea Squid Refillable Swinging Door Jamb Cat Toy'),
  ('696614', 'Meowijuana Refillable Get Hung Moon & Stars Cat Toy'),
  ('696630', 'Meowijuana Refillable Get Lit Cake Cat Toy'),
  ('696646', 'Meowijuana Refillable Get Smashed Llama Pinata Wand Cat Toy'),
  ('696662', 'Meowijuana Refillable Get Wrapped Sushi Cat Toy'),
  ('696678', 'Meowijuana Refillable Get a Ride Magic Carpet Cat Toy'),
  ('696694', 'Meowijuana Christmas Refillable Get Twisted Candy Cane Cat Toy'),
  ('696710', 'Meowijuana Christmas Refillable Get Stuffed Stocking Cat Toy'),
  ('930406', 'Meowijuana Catnip & Silvervine Spray, 3-oz bottle'),
  ('964630', 'Meowijuana Winter Lift Peppermint, Cranberry, Silvervine, & Catnip Blend Catnip, 26-g jar'),
  ('984614', 'Meowijuana Jar of Catnibas Catnip Pawty Mix with Lemongrass Cat Catnip, 60-g bag')
)
select f.chewy_sku, p.master_id, p.short_name, p.brand
from file_skus f
join products p on p.chewy_sku = f.chewy_sku
where p.active = false
order by p.brand, p.short_name;
